function fig = fig10_30()
% This is the machine-generated representation of a Handle Graphics object
% and its children.  Note that handle values may change when these objects
% are re-created. This may cause problems with any callbacks written to
% depend on the value of the handle at the time the object was saved.
% This problem is solved by saving the output as a FIG-file.
%
% To reopen this object, just type the name of the M-file at the MATLAB
% prompt. The M-file and its associated MAT-file must be on your path.
% 
% NOTE: certain newer features in MATLAB may not have been saved in this
% M-file due to limitations of this format, which has been superseded by
% FIG-files.  Figures which have been annotated using the plot editor tools
% are incompatible with the M-file/MAT-file format, and should be saved as
% FIG-files.

load fig10_30

h0 = figure('Units','points', ...
	'Color',[0.8 0.8 0.8], ...
	'Colormap',mat0, ...
	'FileName','D:\book\Matlab\rev2\chap10\fig10_30.m', ...
	'MenuBar','none', ...
	'Name','Menu Test', ...
	'NumberTitle','off', ...
	'PaperPosition',[18 180 576.0000000000001 432.0000000000002], ...
	'PaperUnits','points', ...
	'Position',[199.8620689655173 99.93103448275865 199.8620689655173 99.93103448275865], ...
	'Tag','Fig1', ...
	'ToolBar','none');
h1 = uimenu('Parent',h0, ...
	'Label','&File', ...
	'Tag','Menu1');
h2 = uimenu('Parent',h1, ...
	'Label','&Open', ...
	'Tag','Menu1Item1');
h2 = uimenu('Parent',h1, ...
	'Label','&Save', ...
	'Tag','Menu1Item2');
h2 = uimenu('Parent',h1, ...
	'Callback','disp(''save as...'')', ...
	'Label','Save &As', ...
	'Tag','Menu1Item3');
h2 = uimenu('Parent',h1, ...
	'Callback','close(gcbf)', ...
	'Label','E&xit', ...
	'Separator','on', ...
	'Tag','Menu1Item4');
h1 = uimenu('Parent',h0, ...
	'Label','&Edit', ...
	'Tag','Menu2');
if nargout > 0, fig = h0; end
