function fig = temp()
load temp

h0 = figure('Units','points', ...
   'Color',[0.8 0.8 0.8], ...
   'Colormap',mat0, ...
   'FileName','D:\book\Matlab\rev2\chap10\temp.m', ...
   'MenuBar','none', ...
   'PaperPosition',[18 180 576.0000000000001 432.0000000000002], ...
   'PaperUnits','points', ...
   'Position',[304 16 300 220], ...
   'Tag','Fig1', ...
   'ToolBar','none');
h1 = uimenu('Parent',h0, ...
   'Label','&File', ...
   'Tag','Menu1');
h2 = uimenu('Parent',h1, ...
   'Label','&Open', ...
   'Tag','Menu1Item1');
h2 = uimenu('Parent',h1, ...
   'Label','&Save', ...
   'Tag','Menu1Item2');
h2 = uimenu('Parent',h1, ...
   'Callback','disp(''save as...'')', ...
   'Label','Save &As', ...
   'Tag','Menu1Item3');
h2 = uimenu('Parent',h1, ...
   'Callback','close(gcbf)', ...
   'Label','E&xit', ...
   'Separator','on', ...
   'Tag','Menu1Item4');
h1 = uimenu('Parent',h0, ...
   'Label','&Edit', ...
   'Tag','Menu2');
if nargout > 0, fig = h0; end
