function fig = temp()
% This is the machine-generated representation of a Handle Graphics object
% and its children.  Note that handle values may change when these objects
% are re-created. This may cause problems with any callbacks written to
% depend on the value of the handle at the time the object was saved.
% This problem is solved by saving the output as a FIG-file.
%
% To reopen this object, just type the name of the M-file at the MATLAB
% prompt. The M-file and its associated MAT-file must be on your path.
% 
% NOTE: certain newer features in MATLAB may not have been saved in this
% M-file due to limitations of this format, which has been superseded by
% FIG-files.  Figures which have been annotated using the plot editor tools
% are incompatible with the M-file/MAT-file format, and should be saved as
% FIG-files.

load temp

h0 = figure('Units','points', ...
	'Color',[0.8 0.8 0.8], ...
	'Colormap',mat0, ...
	'FileName','D:\book\Matlab\rev2\chap10\temp.m', ...
	'MenuBar','none', ...
	'PaperPosition',[18 180 576.0000000000001 432.0000000000002], ...
	'PaperUnits','points', ...
	'Position',[304.1379310344829 161.3793103448276 303.5172413793104 225.9310344827587], ...
	'Tag','Fig1', ...
	'ToolBar','none');
h1 = uimenu('Parent',h0, ...
	'Label','&File', ...
	'Tag','FileMenu1');
h2 = uimenu('Parent',h1, ...
	'Label','&Open', ...
	'Tag','OpenMenu1');
h2 = uimenu('Parent',h1, ...
	'Label','&Save', ...
	'Tag','SaveMenu1');
h2 = uimenu('Parent',h1, ...
	'Label','Save &As', ...
	'Tag','SaveAsMenu1');
h2 = uimenu('Parent',h1, ...
	'Label','Exit', ...
	'Tag','ExitMenu1');
h1 = uimenu('Parent',h0, ...
	'Label','Help', ...
	'Tag','HelpMenu1');
h2 = uimenu('Parent',h1, ...
	'Label','About', ...
	'Tag','AboutMenu1');
if nargout > 0, fig = h0; end
