function fig = test_program()
% This is the machine-generated representation of a Handle Graphics object
% and its children.  Note that handle values may change when these objects
% are re-created. This may cause problems with any callbacks written to
% depend on the value of the handle at the time the object was saved.
%
% To reopen this object, just type the name of the M-file at the MATLAB
% prompt. The M-file and its associated MAT-file must be on your path.

load test_program 

h0 = figure('Color',[0.8 0.8 0.8], ...
   'Colormap',mat0, ...
   'PointerShapeCData',mat1, ...
   'Position',[300 300 257 136], ...
   'Tag','Fig1');
h1 = uicontrol('Parent',h0, ...
   'Units','points', ...
   'BackgroundColor',[0.75294117 0.75294117 0.75294117], ...
   'ListboxTop',0, ...
   'Position',[50.896 54.000 63.931 16.758], ...
   'String','Total Clicks: 0', ...
   'Style','text', ...
   'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
   'Units','points', ...
   'Callback','button_clicked', ...
   'ListboxTop',0, ...
   'Position',[49.034 13.034 70.138 20.483], ...
   'String','Push Button', ...
   'Style','pushbutton', ...
   'Tag','Pushbutton1');
if nargout > 0, fig = h0; end
