function test_edit()
% This function creates a text field and an edit box.
% The the associated callback will cause the text 
% field to echo whatever was typed into the edit box.

h0 = figure('Color',[0.8 0.8 0.8], ...
   'Name','Test Edit Box', ...
   'NumberTitle','off', ...
   'Position',[300 300 257 136], ...
   'Tag','Fig1');
h1 = uicontrol('Parent',h0, ...
   'Units','points', ...
   'BackgroundColor',[0.8 0.8 0.8], ...
   'Position',[45 45 70 17], ...
   'String','Echo Text Here', ...
   'Style','text', ...
   'Tag','Label1');
h1 = uicontrol('Parent',h0, ...
   'Units','points', ...
   'BackgroundColor',[1 1 1], ...
   'Callback','test_edit_callback', ...
   'Position',[45 25 70 17], ...
   'String','Type Text Here', ...
   'Style','edit', ...
   'Tag','Edit1');
