function test_radiobutton()
% This function creates a set of radio buttons and a 
% text field.  The the associated callback will cause 
% the text field to display the state of the radio 
% buttons.

h0 = figure('Color',[0.8 0.8 0.8], ...
   'Name','Test Radio Button', ...
   'NumberTitle','off', ...
   'Position',[300 300 257 136], ...
   'Tag','Fig1');
h1 = uicontrol('Parent',h0, ...
   'Units','points', ...
   'BackgroundColor',[0.8 0.8 0.8], ...
   'Position',[45 60 70 15], ...
   'String','Option 1', ...
   'Style','text', ...
   'Tag','Label1');
h1 = uicontrol('Parent',h0, ...
   'Units','points', ...
   'Position',[40 5 80 55], ...
   'Style','frame', ...
   'Tag','Frame1');
h1 = uicontrol('Parent',h0, ...
   'Units','points', ...
   'Callback','test_radiobutton_callback rb1', ...
   'Position',[45 40 70 15], ...
   'String','Option 1', ...
   'Style','radiobutton', ...
   'Value',1, ...
   'Tag','radiobutton1');
h1 = uicontrol('Parent',h0, ...
   'Units','points', ...
   'Callback','test_radiobutton_callback rb2', ...
   'Position',[45 25 70 15], ...
   'String','Option 2', ...
   'Style','radiobutton', ...
   'Value',0, ...
   'Tag','radiobutton2');
h1 = uicontrol('Parent',h0, ...
   'Units','points', ...
   'Callback','test_radiobutton_callback rb3', ...
   'Position',[45 10 70 15], ...
   'String','Option 3', ...
   'Style','radiobutton', ...
   'Value',0, ...
   'Tag','radiobutton3');
